# La bibliothèque Numpy

In [1]:
import numpy as np

Créez à partir d’une liste un array unidimensionnel et vérifiez sa taille et ce qu’il comporte.


In [10]:
arr1=np.array([22,55,77,99],dtype=float)
arr1+arr1
print(arr1.shape, arr1.dtype)
arr1

(4,) float64


array([ 22.,  55.,  77.,  99.])

Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array


In [16]:
arr2=np.array([[2,4,6],[5,7,9]])
arr2

arr3=np.arange(16).reshape(4,4)
arr3**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331],
       [1728, 2197, 2744, 3375]], dtype=int32)

Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.


In [17]:
arr4=np.arange(5,11).reshape(3,2)
np.dot(arr4.T,arr4)

array([[155, 176],
       [176, 200]])

Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [21]:
arr5=np.random.randn(1000)
#np.sort()  np.where()
np.sort(np.where(arr5<0,0,arr5))

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt


In [22]:
arr6=np.random.randn(10000000).reshape(1000000,10)

In [23]:
arr6.shape

(1000000, 10)

In [24]:
np.save("arrayTest.npy",arr6)

In [25]:
np.savetxt("arrayTest.txt",arr6,delimiter=";")

In [28]:
arr7=np.load("arrayTest.npy")

In [30]:
arr7.shape

(1000000, 10)